### ISSUE TITLE
Strange joblib-related errors?

### ISSUE THREAD

**Issue by jchutrue** [alphacsc/alphacsc#26] opened 2019-07-18 14:42 UTC
When I attempted to set `n_jobs` > 1 for univariate CSC, I got an error in the middle of learning:

```
OS: Ubuntu 16.04
joblib version: 0.13.2
alphacsc version: Installed from master branch
```

```python
import numpy as np
import alphacsc
x = np.fromfile('test-channel.dat', dtype='<f8')
fs = 1250
n_trials = 5
n_minutes_per_trial = 0.5
n_samples_per_trial = int(n_minutes_per_trial * 60 * fs)
data = x[:n_samples_per_trial * n_trials].reshape(n_trials, n_samples_per_trial)

_, _, d_hat, z_hat, _ = alphacsc.learn_d_z(data,
                                           n_atoms=10,
                                           n_times_atom=int(fs),
                                           reg=5,
                                           n_iter=20,
                                           solver_z='l-bfgs',
                                           solver_z_kwargs=dict(factr=1e9),
                                           solver_d_kwargs=dict(factr=1e2),
                                           random_state=0,
                                           n_jobs=8,
                                           verbose=10
                                          )
```

```pytb
ValueError                                Traceback (most recent call last)
<ipython-input-39-b352a7f31058> in <module>
     29                                            random_state=0,
     30                                            n_jobs=8,
---> 31                                            verbose=10
     32                                           )
     33 

~/code/alphacsc/alphacsc/learn_d_z.py in learn_d_z(X, n_atoms, n_times_atom, func_d, reg, lmbd_max, n_iter, random_state, n_jobs, solver_z, solver_d_kwargs, solver_z_kwargs, ds_init, ds_init_params, sample_weights, verbose, callback, stopping_pobj)
    164                              solver=solver_z, b_hat_0=b_hat_0,
    165                              solver_kwargs=solver_z_kwargs,
--> 166                              sample_weights=sample_weights)
    167             times.append(time.time() - start)
    168 

~/code/alphacsc/alphacsc/update_z.py in update_z(X, ds, reg, z0, debug, parallel, solver, b_hat_0, solver_kwargs, sample_weights)
     63         my_update_z(X, ds, reg, z0, i, debug, solver, b_hat_0, solver_kwargs,
     64                     sample_weights)
---> 65         for i in np.array_split(np.arange(n_trials), parallel.n_jobs))
     66     z_hat = np.vstack(zhats)
     67 

~/applications/anaconda3/envs/ml/lib/python3.6/site-packages/joblib/parallel.py in __call__(self, iterable)
    932 
    933             with self._backend.retrieval_context():
--> 934                 self.retrieve()
    935             # Make sure that we get a last message telling us we are done
    936             elapsed_time = time.time() - self._start_time

~/applications/anaconda3/envs/ml/lib/python3.6/site-packages/joblib/parallel.py in retrieve(self)
    831             try:
    832                 if getattr(self._backend, 'supports_timeout', False):
--> 833                     self._output.extend(job.get(timeout=self.timeout))
    834                 else:
    835                     self._output.extend(job.get())

~/applications/anaconda3/envs/ml/lib/python3.6/site-packages/joblib/_parallel_backends.py in wrap_future_result(future, timeout)
    519         AsyncResults.get from multiprocessing."""
    520         try:
--> 521             return future.result(timeout=timeout)
    522         except LokyTimeoutError:
    523             raise TimeoutError()

~/applications/anaconda3/envs/ml/lib/python3.6/concurrent/futures/_base.py in result(self, timeout)
    423                 raise CancelledError()
    424             elif self._state == FINISHED:
--> 425                 return self.__get_result()
    426 
    427             self._condition.wait(timeout)

~/applications/anaconda3/envs/ml/lib/python3.6/concurrent/futures/_base.py in __get_result(self)
    382     def __get_result(self):
    383         if self._exception:
--> 384             raise self._exception
    385         else:
    386             return self._result

ValueError: need at least one array to concatenate
```

The strange thing is that I've gotten different kinds of errors running the same code, such as "assignment destination is read-only". However, when I checked the input array flags, everything looked ok: 

```python
data.flags
```

```
  C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : False
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False
```

Moreover, the errors are not always reproducible when I run this code, and I can't figure out why. But in general I encounter much fewer of them if I set `n_jobs=1`

**Comment by jasmainak** [comment] 2019-07-18 16:40
What is `data.shape` for you?

**Comment by jchutrue** [comment] 2019-07-18 16:59
It is `(5, 37500)`

**Comment by TomDLT** [comment] 2019-07-18 17:30
This happens because `n_jobs > n_trials`, I could reproduce on `alphacsc/examples/csc/plot_simulate_csc.py`.
I am on it.

**Comment by TomDLT** [comment] 2019-07-18 17:47
Fixed in cf2c4859bab392ae0e77bb4dd22219da17d63f18.
Thanks for the bug report !

**Comment by jchutrue** [comment] 2019-07-18 18:31
I increased the number of trials so that `n_trials > n_jobs` but I ran into the second error:

```python
ValueError                                Traceback (most recent call last)
<ipython-input-13-ff5ab64a5e45> in <module>
      9                                            random_state=random_state,
     10                                            n_jobs=n_jobs,
---> 11                                            verbose=verbose
     12                                           )

~/code/alphacsc/alphacsc/learn_d_z.py in learn_d_z(X, n_atoms, n_times_atom, func_d, reg, lmbd_max, n_iter, random_state, n_jobs, solver_z, solver_d_kwargs, solver_z_kwargs, ds_init, ds_init_params, sample_weights, verbose, callback, stopping_pobj)
    164                              solver=solver_z, b_hat_0=b_hat_0,
    165                              solver_kwargs=solver_z_kwargs,
--> 166                              sample_weights=sample_weights)
    167             times.append(time.time() - start)
    168 

~/code/alphacsc/alphacsc/update_z.py in update_z(X, ds, reg, z0, debug, parallel, solver, b_hat_0, solver_kwargs, sample_weights)
     64         my_update_z(X, ds, reg, z0, i, debug, solver, b_hat_0, solver_kwargs,
     65                     sample_weights)
---> 66         for i in np.array_split(np.arange(n_trials), n_jobs_used))
     67     z_hat = np.vstack(zhats)
     68 

~/applications/anaconda3/envs/ml/lib/python3.6/site-packages/joblib/parallel.py in __call__(self, iterable)
    932 
    933             with self._backend.retrieval_context():
--> 934                 self.retrieve()
    935             # Make sure that we get a last message telling us we are done
    936             elapsed_time = time.time() - self._start_time

~/applications/anaconda3/envs/ml/lib/python3.6/site-packages/joblib/parallel.py in retrieve(self)
    831             try:
    832                 if getattr(self._backend, 'supports_timeout', False):
--> 833                     self._output.extend(job.get(timeout=self.timeout))
    834                 else:
    835                     self._output.extend(job.get())

~/applications/anaconda3/envs/ml/lib/python3.6/site-packages/joblib/_parallel_backends.py in wrap_future_result(future, timeout)
    519         AsyncResults.get from multiprocessing."""
    520         try:
--> 521             return future.result(timeout=timeout)
    522         except LokyTimeoutError:
    523             raise TimeoutError()

~/applications/anaconda3/envs/ml/lib/python3.6/concurrent/futures/_base.py in result(self, timeout)
    430                 raise CancelledError()
    431             elif self._state == FINISHED:
--> 432                 return self.__get_result()
    433             else:
    434                 raise TimeoutError()

~/applications/anaconda3/envs/ml/lib/python3.6/concurrent/futures/_base.py in __get_result(self)
    382     def __get_result(self):
    383         if self._exception:
--> 384             raise self._exception
    385         else:
    386             return self._result

ValueError: assignment destination is read-only

```

**Comment by TomDLT** [comment] 2019-07-18 20:22
So it turns out that the `reshape` operation does not necessarily trigger a copy if the data is contiguous.
I could reproduce for instance with `n_atoms=1`.

I fixed it in e1350277d0c253dc37e0d28df60c30e8e792d22b by forcing a copy (as it was already the case for ISTA and FISTA solvers but not for L-BFGS).

Tell me if it does fix your issue.

**Comment by jchutrue** [comment] 2019-07-18 21:42
Fantastic, it works now. Thanks for the quick fixes!

**Comment by TomDLT** [comment] 2019-07-18 22:30
Thanks for the report !

**Closed by TomDLT** 2019-07-18 22:30 UTC
